name: Compilar CloakV4

on:
  workflow_dispatch: # Ativa o botão manual

jobs:
  build-windows:
    runs-on: windows-2022
    
    steps:
    - name: Baixar o codigo fonte
      uses: actions/checkout@v4
      with:
        submodules: recursive # Garante que dependências internas do Git venham junto

    - name: Configurar as ferramentas do Visual Studio (MSVC)
      uses: ilammy/msvc-dev-cmd@v1 # Ativa o compilador oficial da Microsoft no terminal do GitHub

    - name: Configurar o CMake e rodar o vcpkg
      shell: pwsh
      run: |
        # O repositório usa o vcpkg embutido do GitHub Actions através do arquivo de ferramentas do CMake
        cmake -B build -S . `
          -DCMAKE_BUILD_TYPE=Release `
          -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake" `
          -DVCPKG_TARGET_TRIPLET=x64-windows

    - name: Compilar o executavel
      run: cmake --build build --config Release

    - name: Guardar o resultado (.exe)
      uses: actions/upload-artifact@v4
      with:
        name: CloakV4-Windows-x64
        path: |
          build/bin/Release/
          bin/Release/
